# Generated by Django 3.2.8 on 2021-10-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, verbose_name='Producto')),
                ('precio', models.IntegerField(default=0)),
                ('proveedor', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
