# Generated by Django 3.2.8 on 2021-10-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre Producto'),
        ),
    ]
