# Generated by Django 3.2.8 on 2021-10-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0002_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('idFarmacia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45)),
                ('cod_sede', models.CharField(max_length=45)),
            ],
        ),
    ]
