# Generated by Django 3.2.8 on 2021-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0004_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=80, null=True)),
                ('telefono', models.BigIntegerField()),
            ],
        ),
    ]
