# Generated by Django 3.2.8 on 2021-10-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvApp', '0005_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del cliente')),
                ('apellidos', models.CharField(max_length=120, verbose_name='Apellidos del cliente')),
                ('email', models.EmailField(default='No registra', max_length=254)),
                ('telefono', models.BigIntegerField(null=True)),
            ],
        ),
    ]
